 var ApiError={
 
    INVALID_ID : "ID_INVALID",
   INVALID_TICKER :"TICKER_INVALID",
     INVALID_TOKEN :"TOKEN_INVALID",
    INVALID_CREDENTIAL: "CREDENTIAL_INVALID",

    NOT_FOUND_CREDENTIAL : "CREDENTIAL_NOT_FOUND",
    NOT_FOUND_USER: "USER_NOT_FOUND",
    NOT_FOUND_STOCK :"STOCK_NOT_FOUND",

    EXIST_USER : "USER_EXISTED",
    EXIST_RELATION : "RELATION_EXISTED",
    EXIST_CREDENTIAL : "CREDENTIAL_EXISTED"

 };
 
 module.exports = ApiError;
